[package]
name = "s2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
indoc = "1.0.7"
pretty_assertions = "1.3.0"
